### PR TITLE
Fix active window not working on the framebuffer

### LINKED ISSUE #92: Unexpected null screen in Linux framebuffer backend
After merging [#88](https://github.com/sysprog21/mado/pull/88), I encountered issues while executing fbdev. To identify the source of the error, I conducted several experiments. I observed that the error originates from the `twin_screen_update` function, as I was able to successfully execute fbdev using the original `twin_screen_update` function.

To resolve this issue, I modified the code introduced in [#88](https://github.com/sysprog21/mado/pull/88) to ensure that the updated `twin_screen_update` function is compatible with fbdev. Below are the modifications I made:
```diff
static twin_pixmap_t *twin_active_pixmap(twin_screen_t *screen,
                                         twin_pixmap_t **active_pix)
{
    twin_pixmap_t *p = NULL, *prev_active_pix = NULL;
    /*
     * Identify the previously active pixel map and the currently active pixel
     * map, which is on the topmost layer.
     */
    for (p = screen->bottom; p; p = p->up) {
        if (p->window->active == true) {
            prev_active_pix = p;
            prev_active_pix->window->active = false;
        }
        (*active_pix) = p;
    }
+    if(*active_pix)
+        (*active_pix)->window->active = true;
-   (*active_pix)->window->active = true;
    return prev_active_pix;
}
...
        prev_active_pix = twin_active_pixmap(screen, &active_pix);
	//active_pix = prev_active_pix;
        /*
         * Mark the previously active pixel map as damaged to update its
         * changes.
         */
-       if (prev_active_pix && active_pix != prev_active_pix)
+       if ((prev_active_pix && active_pix != prev_active_pix) && prev_active_pix){
            twin_pixmap_damage(prev_active_pix, 0, 0, prev_active_pix->width, prev_active_pix->height);
            twin_window_draw(prev_active_pix->window);
        }

        /* Mark the active pixel map as damaged to update its changes. */
+       if(active_pix){
+            twin_pixmap_damage(active_pix, 0, 0, active_pix->width,active_pix->height);
+            twin_window_draw(active_pix->window);
+       }
-        twin_pixmap_damage(active_pix, 0, 0, active_pix->width,active_pix->height);
-        twin_window_draw(active_pix->window);
```

The condition `if(*active_pix)` ensures that `*active_pix` is valid, as I previously encountered failures in this part of the code. Similarly, `if(active_pix)` verifies that `active_pix` is not NULL. These modifications are designed to prevent unexpected situations from occurring. Finally, I obtained the output from my VM.
messageImage_1737563693437

If I eliminate the code below, I am able to successfully run fbdev.
```diff
/* Mark the active pixel map as damaged to update its changes. */
- twin_pixmap_damage(active_pix, 0, 0, active_pix->width,
-                   active_pix->height);
- twin_window_draw(active_pix->window);
```
https://github.com/user-attachments/assets/191f8632-2a75-48df-8708-3512639a8825

### PR DESCRIPTION
**Pull request by weihsinyeh**
Remove the inefficiently function twin_active_pixmap(). This function finds the currently and previously active window pixel map by traversing the list of pixel maps. This function will be called every time the screen needs to be updated. Set the active variable of the window only when the window's event TwinEventButtonDown is triggered to avoid redundant operations. Additionally, implement the function twin_window_active_paint() to only repaint the title bar instead of calling the function twin_window_draw() to indirectly call the function twin_window_frame to repaint the title bar of the window.

Close #92

### CODE REVIEW

File: src/window.c [hunk 1]
```diff
@@ -156,6 +156,19 @@ void twin_window_set_name(twin_window_t *window, const char *name)
         strcpy(window->name, name);
     twin_window_draw(window);
 }
+static void twin_window_active_paint(twin_window_t *window)
```
Comment (shengwen-tw) [inline src/window.c:159]: Missing one empty line here.

**Comment by shengwen-tw** [comment]
Looks legitimate to me, but since I am not familiar with recent developments, I would like to see if others have different opinions.

**Comment by huaxinliao** [comment]
I confirmed that fbdev can run on a VM with Ubuntu 24.04 and a Pi 3B. Below is the output from the Pi 3B.

https://github.com/user-attachments/assets/98af8b4d-4056-489b-8cbd-ec230a42ba0f

**Comment by weihsinyeh** [comment]
The title bars of the active and inactive window don't display on the video.

File: src/window.c [hunk 2]
```diff
@@ -156,6 +156,19 @@ void twin_window_set_name(twin_window_t *window, const char *name)
...
+{
+    twin_fixed_t bw = twin_int_to_fixed(TWIN_TITLE_BW);
+    twin_path_t *path = twin_path_create();
+    twin_fixed_t bw_2 = bw / 2;
+    if (window->active) {
+        twin_paint_path(window->pixmap, TWIN_ACTIVE_BG, path);
+        twin_paint_stroke(window->pixmap, TWIN_ACTIVE_BORDER, path, bw_2 * 2);
```
Comment (ndsl7109256) [inline src/window.c:166]: The reason that the title bars don't show is because you need to determine the trajectory you want to paint first and then use `twin_paint_path ` or `twin_paint_stroke` to fill the graph or draw the border.

I think the `twin_window_active_paint` would be like
```c
static void twin_window_active_paint(twin_window_t *window)
{
    // Ignore the above
    twin_path_t *path = twin_path_create();
    twin_path_move(path, c_left, c_top);
    twin_path_draw(path, c_right, c_top);
    twin_path_curve(path, c_right, w_top + t_arc_1, c_right - t_arc_1, w_top,
                    c_right - t_h, w_top);
    twin_path_draw(path, c_left + t_h, w_top);
    twin_path_curve(path, c_left + t_arc_1, w_top, c_left, w_top + t_arc_1,
                    c_left, c_top);
    twin_path_close(path);
    if (window->active) {
        twin_paint_path(window->pixmap, TWIN_ACTIVE_BG, path);
        twin_paint_stroke(window->pixmap, TWIN_ACTIVE_BORDER, path, bw_2 * 2);
    } else {
        twin_paint_path(window->pixmap, TWIN_INACTIVE_BG, path);
        twin_paint_stroke(window->pixmap, TWIN_INACTIVE_BORDER, path, bw_2 * 2);
    }
}
```

Comment (ndsl7109256) [reply src/window.c:166]: How about adding a `twin_path_t *label_path` member to `twin_window_t`? In `twin_window_frame`, you could initialize the path, and in `twin_window_active_paint`, determine the color to paint when the top window changes. Then you can still apply the colors in the same logic.

```c
static void twin_window_active_paint(twin_window_t *window)
{
    twin_fixed_t bw = twin_int_to_fixed(TWIN_TITLE_BW);
    twin_path_t *path = twin_path_create();
    twin_fixed_t bw_2 = bw / 2;
    if (window->active) {
        twin_paint_path(window->pixmap, TWIN_ACTIVE_BG, window->label_path);
        twin_paint_stroke(window->pixmap, TWIN_ACTIVE_BORDER, window->label_path, bw_2 * 2);
    } else {
        twin_paint_path(window->pixmap, TWIN_INACTIVE_BG, window->label_path);
        twin_paint_stroke(window->pixmap, TWIN_INACTIVE_BORDER, window->label_path, bw_2 * 2);
    }
}

static void twin_window_frame(twin_window_t *window)
{
    /* Ignore the above */
    window->label_path = twin_path_create();
    twin_path_move(window->label_path, c_left, c_top);
    twin_path_draw(window->label_path, c_right, c_top);
    twin_path_curve(window->label_path, c_right, w_top + t_arc_1, c_right - t_arc_1, w_top,
                    c_right - t_h, w_top);
    twin_path_draw(window->label_path, c_left + t_h, w_top);
    twin_path_curve(window->label_path, c_left + t_arc_1, w_top, c_left, w_top + t_arc_1,
                    c_left, c_top);
    twin_path_close(window->label_path);
    twin_window_active_paint(window);
}

Comment (weihsinyeh) [reply src/window.c]: OK, Thank you! we can try which one can work on framebuffer.

**Comment by huaxinliao** [comment]
Here's the output from [512a891](https://github.com/sysprog21/mado/pull/94/commits/512a89183863f4752e5ee3e75c0efb2db0d8b77b) on the Pi 3B.

https://github.com/user-attachments/assets/36c1e04d-a39e-4433-8e86-88bb4d5d2795

File: include/twin.h [hunk 3]
```diff
@@ -1173,6 +1173,8 @@ void twin_window_damage(twin_window_t *window,
                         twin_coord_t right,
                         twin_coord_t bottom);
 
+void twin_window_frame(twin_window_t *window);
```
Comment (jserv) [inline include/twin.h:1176]: Add comments.

File: src/window.c [hunk 4]
```diff
@@ -157,7 +157,7 @@ void twin_window_set_name(twin_window_t *window, const char *name)
     twin_window_draw(window);
 }
 
-static void twin_window_frame(twin_window_t *window)
+void twin_window_frame(twin_window_t *window)
```
Comment (ndsl7109256) [inline src/window.c:160]: Why did you change this function from static to non-static?

**Comment by weihsinyeh** [comment]
At the beginning, is it reasonable for there to be no active window displayed?

**Comment by ndsl7109256** [comment]
> At the beginning, is it reasonable for there to be no active window displayed?

On macOS, there is always an active window at the top, but I'm not sure how it performs on other platforms. Besides, I noticed that if I click the top window first, it doesn't get activated.

https://github.com/user-attachments/assets/816ff8ef-3216-4e0c-9c9c-5140ec20925e

**Comment by huaxinliao** [comment]
Here's the output of fbdev from commit [e80e45e](https://github.com/sysprog21/mado/commit/e80e45eaa6015f82d05f8f3af725bd95c110c35d) on the Raspberry Pi 3B.

https://github.com/user-attachments/assets/db025f76-875a-46f6-b852-f4a461085bae

**Review by huaxinliao — APPROVED** [review]

**Comment by jserv** [comment]
Thank @weihsinyeh for contributing!
